// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmzCRZRmz6p4pkCZ9IuoI2sktZodu-UeE',
    appId: '1:622099708370:web:1a419f9918866787b1700b',
    messagingSenderId: '622099708370',
    projectId: 'emindmatterssystem',
    authDomain: 'emindmatterssystem.firebaseapp.com',
    storageBucket: 'emindmatterssystem.appspot.com',
    measurementId: 'G-EBEEDTKCDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxl6qrGiQNdIMBXYmWz8gRa5fu1BHgNPc',
    appId: '1:622099708370:android:dca1941410c3db66b1700b',
    messagingSenderId: '622099708370',
    projectId: 'emindmatterssystem',
    storageBucket: 'emindmatterssystem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtjLFiDskaOxKPLbqhKnAfD1In56V0HTU',
    appId: '1:622099708370:ios:0763c5a4a094742cb1700b',
    messagingSenderId: '622099708370',
    projectId: 'emindmatterssystem',
    storageBucket: 'emindmatterssystem.appspot.com',
    iosBundleId: 'com.example.emindmatterssystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtjLFiDskaOxKPLbqhKnAfD1In56V0HTU',
    appId: '1:622099708370:ios:82d6a94973da6c6eb1700b',
    messagingSenderId: '622099708370',
    projectId: 'emindmatterssystem',
    storageBucket: 'emindmatterssystem.appspot.com',
    iosBundleId: 'com.example.emindmatterssystem.RunnerTests',
  );
}
